version: '3.1'

services:
  # Use postgres/example user/password credentials
  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
